import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.chamados.createMany({
    data: [
      // SEED Isabella Cabrera

      {
        descricao: "Falha grave no acesso ao banco de dados",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 1,
        responsavelId: 3,
      },
      {
        descricao: "Sistema de faturamento fora do ar",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 5,
        responsavelId: 1,
      },
      {
        descricao: "Perda de dados de aluno no sistema de gestão escolar",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 2,
        responsavelId: 4,
      },
      {
        descricao: "Vazamento de informacoes sensiveis de alunos",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 3,
        responsavelId: 2,
      },
      {
        descricao: "Bloqueio total de conta de professor no sistema",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 4,
        responsavelId: 5,
      },
      {
        descricao:
          "Firewall bloqueando trafego essencial para o sistema educacional",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 1,
        responsavelId: 2,
      },
      {
        descricao: "Erro na folha de pagamento dos funcionários da escola",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 5,
        responsavelId: 3,
      },
      {
        descricao:
          "Servidor web principal inacessivel para acesso ao portal do aluno",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 2,
        responsavelId: 1,
      },
      {
        descricao: "Phishing reportado por varios funcionários da escola",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 3,
        responsavelId: 4,
      },
      {
        descricao: "Ambiente de testes indisponivel para alunos",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 4,
        responsavelId: 3,
      },
      {
        descricao: "Troca de bateria de notebook corporativo para professor",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 1,
        responsavelId: 4,
      },
      {
        descricao: "Monitor com pixel morto ou defeito na sala de informática",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 2,
      },
      {
        descricao: "Headset novo para call center da secretaria",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 2,
        responsavelId: 5,
      },
      {
        descricao: "Manutencao preventiva em PC antigo na sala de professores",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 3,
        responsavelId: 1,
      },
      {
        descricao: "Problemas com webcam durante reuniao",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 4,
        responsavelId: 2,
      },
      {
        descricao: "Configuracao de impressora de rede em novo andar da escola",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 1,
        responsavelId: 5,
      },
      {
        descricao: "Solicitacao de adaptador USB-C para o projetor da sala 32",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 4,
      },
      {
        descricao:
          "Substituicao de cabo de rede danificado na sala de informática 02",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 2,
        responsavelId: 3,
      },
      {
        descricao: "Limpeza e otimizacao de maquina lenta no Maker",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 3,
        responsavelId: 5,
      },
      {
        descricao: "Instalacao de mouse pad ergonomico para o diretor",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 4,
        responsavelId: 1,
      },
      {
        descricao:
          "Permissao para instalar Chrome Extensions nos computadores usados pelos alunos",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 1,
        responsavelId: 2,
      },
      {
        descricao: "Solicitacao de acesso a curso online para aluno",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 5,
        responsavelId: 4,
      },
      {
        descricao: "Mudanca de grupo de seguranca no AD da escola",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 2,
        responsavelId: 1,
      },
      {
        descricao: "Criacao de conta para estagiario de TI",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 3,
        responsavelId: 5,
      },
      {
        descricao: "Revogacao de acesso de ex-colaborador da escola",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 4,
        responsavelId: 3,
      },
      {
        descricao:
          "Criacao de e-mail generico para setor administrativo da escola",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 1,
        responsavelId: 4,
      },
      {
        descricao: "Ajuste no limite de armazenamento em nuvem para alunos",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 5,
        responsavelId: 2,
      },
      {
        descricao:
          "Acesso a documentacao interna desatualizada no portal da escola",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 2,
        responsavelId: 3,
      },
      {
        descricao:
          "Revisao de permissoes de pastas compartilhadas no sistema de gestão escolar",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 3,
        responsavelId: 1,
      },
      {
        descricao: "Cadastro de número de telefone em ramal da secretaria",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 4,
        responsavelId: 5,
      },
      {
        descricao:
          "Relatorio de bugs no novo módulo do sistema de gestão escolar",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 1,
        responsavelId: 5,
      },
      {
        descricao: "Dificuldade de conexao Wi-Fi no 3 andar da escola",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 3,
      },
      {
        descricao: "Configuracao de MFA para professores",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 2,
        responsavelId: 4,
      },
      {
        descricao:
          "Erro na geracao de nota fiscal eletronica no sistema financeiro escolar",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 3,
        responsavelId: 1,
      },
      {
        descricao:
          "Solicitacao de aumento de memoria RAM para servidor de dados",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 4,
        responsavelId: 2,
      },
      {
        descricao: "Problema na sincronizacao do calendario",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 1,
        responsavelId: 3,
      },
      {
        descricao: "Software 3D travando",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 5,
        responsavelId: 4,
      },
      {
        descricao:
          "Implementacao de novo padrao de nomenclatura de arquivos escolares",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 2,
        responsavelId: 5,
      },
      {
        descricao: "Licenca de software de laboratório de informática expirou",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 3,
        responsavelId: 2,
      },
      {
        descricao: "Tela do monitor quebrada",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 4,
        responsavelId: 1,
      },
      {
        descricao: "Monitor quebrado na sala do diretor",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 1,
        responsavelId: 3,
      },
      {
        descricao: "Lentidao no sistema de vendas de materiais didáticos",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 5,
        responsavelId: 2,
      },
      {
        descricao: "Redefinicao de senha negado",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 2,
        responsavelId: 4,
      },
      {
        descricao: "Monitor com metade da tela preta ",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 3,
        responsavelId: 5,
      },
      {
        descricao: "Criacao de subdominio para novo portal de alunos",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 4,
        responsavelId: 1,
      },
      {
        descricao: "Hardwares da sala de informática 05 precisam de limpeza",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 1,
        responsavelId: 4,
      },
      {
        descricao: "Atualizacao de BIOS em computador da sala 26",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 3,
      },
      {
        descricao:
          "Erro de integração entre sistemas de gestão acadêmica e financeiro",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 2,
        responsavelId: 1,
      },
      {
        descricao: "Monitor travado na tela de bloqueio",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 3,
        responsavelId: 2,
      },
      {
        descricao: "Problemas de audio VOIP",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 4,
        responsavelId: 5,
      },
      {
        descricao: "Hardware quebrado",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 5,
        responsavelId: 1,
      },
      {
        descricao: "Nova funcionalidade no ERP escolar",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 2,
        responsavelId: 4,
      },
      {
        descricao: "Erro de calculo em planilha de controle de matrícula",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 3,
        responsavelId: 5,
      },
      {
        descricao: "Instalacao de plugin para sistema de gestão escolar",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 4,
        responsavelId: 2,
      },
      {
        descricao: "Sistema de projetos acadêmicos lento",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 1,
        responsavelId: 3,
      },
      {
        descricao: "Migracao de dados entre plataformas de gestão escolar",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 4,
      },
      {
        descricao: "Assinatura digital de PDF não funciona",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 2,
        responsavelId: 1,
      },
      {
        descricao: "Incompatibilidade com Windows 11",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 3,
        responsavelId: 5,
      },
      {
        descricao: "Computador travado no laboratório 8",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 4,
        responsavelId: 3,
      },
      {
        descricao: "Erro ao acessar o portal educacional",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 1,
        responsavelId: 2,
      },
      {
        descricao: "Telefone VOIP da secretaria sem sinal",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 2,
      },
      {
        descricao: "Manutencao do nobreak",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 2,
        responsavelId: 4,
      },
      {
        descricao: "Configuracao de rede do laboratório 15",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 3,
        responsavelId: 1,
      },
      {
        descricao: "Queda de energia no datacenter",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 4,
        responsavelId: 5,
      },
      {
        descricao: "Internet instável no prédio principal",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 1,
        responsavelId: 4,
      },
      {
        descricao: "Otimizacao de rotas de rede",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 3,
      },
      {
        descricao: "Falha no RDP",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 2,
        responsavelId: 1,
      },
      {
        descricao: "Renovacao de servico de Cloud",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 3,
        responsavelId: 4,
      },
      {
        descricao: "Sistema de monitoramento offline",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 4,
        responsavelId: 2,
      },
      {
        descricao: "Câmeras da entreda da escola não estão funcionando",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 1,
        responsavelId: 5,
      },
      {
        descricao: "Computador infectado por ransomware",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 5,
        responsavelId: 3,
      },
      {
        descricao: "Senhas de acesso da sala de documentos comprometida",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 2,
        responsavelId: 5,
      },
      {
        descricao: "Revisao de politica de seguranca",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 3,
        responsavelId: 4,
      },
      {
        descricao: "Novo token de seguranca fisico",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 4,
        responsavelId: 1,
      },
      {
        descricao: "Camera CFTV com problema",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 1,
        responsavelId: 2,
      },
      {
        descricao: "Monitor da sala de aula 23 não liga",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 4,
      },
      {
        descricao: "Senhas de acesso dos alunos da sala 14 foram vazadas",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 2,
        responsavelId: 3,
      },
      {
        descricao: "Monitor quebrado",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 3,
        responsavelId: 1,
      },
      {
        descricao: "Hardware precisa de limpeza na sala 30",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 4,
        responsavelId: 5,
      },
      {
        descricao: "Atualizacao de firmware de switches",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 1,
        responsavelId: 3,
      },
      // adiciona mais 50 chamados
      {
        descricao: "Projetor da Sala de Aula 10 não exibe imagem",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 6,
        responsavelId: 3,
      },
      {
        descricao: "Lentidão extrema no computador da Biblioteca",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 7,
        responsavelId: 1,
      },
      {
        descricao: "Recuperação de arquivo de planejamento excluído acidentalmente",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 8,
        responsavelId: 4,
      },
      {
        descricao: "Falha de login no sistema de notas para vários professores",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 9,
        responsavelId: 2,
      },
      {
        descricao: "Vírus detectado em notebook de professor (solicita limpeza)",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 10,
        responsavelId: 5,
      },
      {
        descricao: "Conexão VPN falhando para acesso remoto ao sistema escolar",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 6,
        responsavelId: 2,
      },
      {
        descricao: "Monitor da sala da direção quebrado. Troca imediata com a recuperação de dados",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 7,
        responsavelId: 3,
      },
      {
        descricao: "Sala 22 com problema no projetor",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 8,
        responsavelId: 1,
      },
      {
        descricao: "Alerta de segurança sobre vulnerabilidade no portal do professor",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 9,
        responsavelId: 4,
      },
      {
        descricao: "Backup diário do sistema de gestão falhou",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 10,
        responsavelId: 3,
      },

      {
        descricao: "Instalação de monitores no laboratório de Artes",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 6,
        responsavelId: 4,
      },
      {
        descricao: "Troca de monitor quebrado na biblioteca",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 7,
        responsavelId: 2,
      },
      {
        descricao: "Limpeza de hardware",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 8,
        responsavelId: 5,
      },
      {
        descricao: "Monitor deu tela preta",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 9,
        responsavelId: 1,
      },
      {
        descricao: "Solicitação de teclado e mouse ergonômicos para a Coordenação",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 10,
        responsavelId: 2,
      },
      {
        descricao: "Cabo de força do PC da Sala 15 está danificado",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 6,
        responsavelId: 5,
      },
      {
        descricao: "Limpeza interna de computador acumulando poeira na Tesouraria",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 7,
        responsavelId: 4,
      },
      {
        descricao: "Configuração de atalho de rede para pasta compartilhada",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 8,
        responsavelId: 3,
      },
      {
        descricao: "Ajuste de permissão de gravação em pendrive no computador da Recepção",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 9,
        responsavelId: 5,
      },
      {
        descricao: "Problema no microfone do PC da Sala de Reuniões",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 10,
        responsavelId: 1,
      },

      {
        descricao: "Criação de lista de distribuição de e-mail para Pais do Ensino Médio",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 6,
        responsavelId: 2,
      },
      {
        descricao:
          "Solicitação de acesso a um relatório antigo no sistema financeiro",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 7,
        responsavelId: 4,
      },
      {
        descricao: "Mudança de nome de usuário no sistema interno (casamento)",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 8,
        responsavelId: 1,
      },
      {
        descricao:
          "Criação de conta de acesso temporário para auditoria externa",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 9,
        responsavelId: 5,
      },
      {
        descricao: "Revogação de acesso de estagiário que terminou o contrato",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 10,
        responsavelId: 3,
      },
      {
        descricao: "Atualização de dados cadastrais de professor na intranet",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 6,
        responsavelId: 4,
      },
      {
        descricao:
          "Ajuste no formato da data de nascimento no relatório de alunos",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 7,
        responsavelId: 2,
      },
      {
        descricao:
          "Solicitação de ícone de atalho na área de trabalho para sistema de RH",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 8,
        responsavelId: 3,
      },
      {
        descricao:
          "Documentação da nova política de uso de software desatualizada",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 9,
        responsavelId: 1,
      },
      {
        descricao:
          "Configuração de notificação por e-mail para aprovação de férias",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 10,
        responsavelId: 5,
      },

      {
        descricao: "Serviço de DNS da escola falhando intermitentemente",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 6,
        responsavelId: 5,
      },
      {
        descricao: "Internet caindo a cada 10 minutos na sala dos professores",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 7,
        responsavelId: 3,
      },
      {
        descricao:
          "Configuração de acesso a pastas de rede via celular (mobile)",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 8,
        responsavelId: 4,
      },
      {
        descricao:
          "Erro crítico na API de comunicação entre Moodle e sistema de gestão",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 9,
        responsavelId: 1,
      },
      {
        descricao:
          "Solicitação de licenças adicionais para software de robótica",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 10,
        responsavelId: 2,
      },
      {
        descricao:
          "Problema de incompatibilidade após atualização de sistema operacional",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 6,
        responsavelId: 3,
      },
      {
        descricao: "Software de agendamento de salas de aula está fora do ar",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 7,
        responsavelId: 4,
      },
      {
        descricao:
          "Implementação de novo certificado SSL para o portal do aluno",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 8,
        responsavelId: 5,
      },
      {
        descricao:
          "Computador da sala de informática 03 não inicializa (tela preta)",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 9,
        responsavelId: 2,
      },
      {
        descricao:
          "Substituição de cartucho de tinta da impressora do setor de Compras",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 10,
        responsavelId: 1,
      },

      {
        descricao: "Switch de rede da ala C parou de funcionar",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 6,
        responsavelId: 3,
      },
      {
        descricao: "Lentidão no carregamento de páginas da intranet (portal interno)",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 7,
        responsavelId: 2,
      },
      {
        descricao: "Redefinição de senha do Wi-Fi para professor novo",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 8,
        responsavelId: 4,
      },
      {
        descricao: "Monitor piscando intermitentemente no laboratório de Química",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 9,
        responsavelId: 5,
      },
      {
        descricao: "Criação de repositório Git para projetos dos alunos de T.I.",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 10,
        responsavelId: 1,
      },
      {
        descricao: "Firewall bloqueando acesso a site de pesquisa educacional específico",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 6,
        responsavelId: 4,
      },
      {
        descricao: "Atualização de driver de placa de vídeo em computador de design",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 7,
        responsavelId: 3,
      },
      {
        descricao: "Erro de formatação na exportação de lista de presença",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 8,
        responsavelId: 1,
      },
      {
        descricao: "Computador da Coordenadora desligando sozinho",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 9,
        responsavelId: 2,
      },
      {
        descricao: "Problema na câmera IP da área externa (não transmite vídeo)",
        status: "concluido",
        prioridade: "media",
        criadoPorId: 10,
        responsavelId: 5,
      },

      // SEED Ana Ramos

      {
        descricao: "Computador nao liga",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 1,
        responsavelId: 2,
      },
      {
        descricao: "Nao consigo acessar o Wi-Fi da escola",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 3,
        responsavelId: 4,
      },
      {
        descricao: "Impressora da secretaria esta offline",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 5,
        responsavelId: 2,
      },
      {
        descricao: "Monitor secundario nao reconhecido",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 6,
        responsavelId: 4,
      },
      {
        descricao:
          "Monitor da sala 13 precisa da instalacao do software DesignPro",
        status: "em_andamento",
        prioridade: "baixa",
        criadoPorId: 7,
        responsavelId: 8,
      },
      {
        descricao: "Mouse sem fio parou de funcionar",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 9,
        responsavelId: 10,
      },
      {
        descricao: "Esqueci minha senha do sistema interno",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 11,
        responsavelId: 8,
      },
      {
        descricao: "Conta bloqueada apos tentativas de login",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 12,
        responsavelId: 10,
      },
      {
        descricao: "Acesso a pasta compartilhada da Turma do 2B",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 13,
        responsavelId: 2,
      },
      {
        descricao: "Email suspeito recebido na secretaria (phishing)",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 14,
        responsavelId: 4,
      },
      {
        descricao:
          "Os arquivos não estão sendo armazenados no sistema da escola",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 15,
        responsavelId: 8,
      },
      {
        descricao: "Computador da secretaria não conecta a rede escolar",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 16,
        responsavelId: 10,
      },
      {
        descricao: "Botao de exportar relatorio não aparece",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 17,
        responsavelId: 2,
      },
      {
        descricao: "Sugestao de melhoria: filtro por data",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 18,
        responsavelId: 4,
      },
      {
        descricao: "Erro ao sincronizar dados com a nuvem",
        status: "aberto",
        prioridade: "baixa",
        criadoPorId: 19,
        responsavelId: 8,
      },
      {
        descricao: "Notebook do professor sem áudio",
        status: "em_andamento",
        prioridade: "alta",
        criadoPorId: 20,
        responsavelId: 10,
      },
      {
        descricao: "O envio automático dos boletos aos pais falhou",
        status: "aberto",
        prioridade: "media",
        criadoPorId: 21,
        responsavelId: 2,
      },
      {
        descricao: "Hardware do laboratório 5 precisa ser consertado",
        status: "aberto",
        prioridade: "alta",
        criadoPorId: 22,
        responsavelId: 4,
      },
      {
        descricao: "Reenvio de nota fiscal dos materiais aos pais dos alunos",
        status: "concluido",
        prioridade: "baixa",
        criadoPorId: 23,
        responsavelId: 8,
      },
      {
        descricao: "Monitor da sala 18 não liga ",
        status: "em_andamento",
        prioridade: "media",
        criadoPorId: 24,
        responsavelId: 10,
      },
    ],
    skipDuplicates: true,
  });

  console.log("Seed unificado concluído!");
}

await prisma.usuario.createMany({
  data: [
    {
      id: 1,
      nome: "Ana Silva",
      email: "ana@empresa.com",
      senha: "123456",
      tipo: "admin",
    },
    {
      id: 2,
      nome: "Bruno Costa",
      email: "bruno@empresa.com",
      senha: "123456",
      tipo: "suporte",
    },
    {
      id: 3,
      nome: "Carla Souza",
      email: "carla@empresa.com",
      senha: "123456",
      tipo: "suporte",
    },
    {
      id: 4,
      nome: "Daniel Lima",
      email: "daniel@empresa.com",
      senha: "123456",
      tipo: "gestor",
    },
    {
      id: 5,
      nome: "Eduardo Rocha",
      email: "eduardo@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 6,
      nome: "Fernanda Alves",
      email: "fernanda@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 7,
      nome: "Gabriel Pinto",
      email: "gabriel@empresa.com",
      senha: "123456",
      tipo: "suporte",
    },
    {
      id: 8,
      nome: "Helena Ramos",
      email: "helena@empresa.com",
      senha: "123456",
      tipo: "suporte",
    },
    {
      id: 9,
      nome: "Igor Carvalho",
      email: "igor@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 10,
      nome: "Julia Martins",
      email: "julia@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 11,
      nome: "Kleber Santos",
      email: "kleber@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 12,
      nome: "Larissa Nogueira",
      email: "larissa@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 13,
      nome: "Marcos Paulo",
      email: "marcos@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 14,
      nome: "Natália Farias",
      email: "natalia@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 15,
      nome: "Otávio Mendes",
      email: "otavio@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 16,
      nome: "Paula Godoi",
      email: "paula@empresa.com",
      senha: "123456",
      tipo: "gestor",
    },
    {
      id: 17,
      nome: "Ricardo Moraes",
      email: "ricardo@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 18,
      nome: "Sandra Moreira",
      email: "sandra@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 19,
      nome: "Thiago Cunha",
      email: "thiago@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 20,
      nome: "Ursula Prado",
      email: "ursula@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 21,
      nome: "Vitor Ferreira",
      email: "vitor@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 22,
      nome: "Willian Barros",
      email: "willian@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 23,
      nome: "Xavier Gomes",
      email: "xavier@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 24,
      nome: "Yasmin Duarte",
      email: "yasmin@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
    {
      id: 25,
      nome: "Zuleica Andrade",
      email: "zuleica@empresa.com",
      senha: "123456",
      tipo: "colaborador",
    },
  ],
  skipDuplicates: true,
});

console.log("Usuários criados!");

main()
  .catch((e) => {
    console.error("Erro no seed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
